all:
	sudo g++ -std=c++0x inc/cLang.h inc/codeclear.h inc/errorresponder.h inc/FCGI_Stream.h inc/includes.h inc/main.h inc/logfile.h inc/SQLconnector.h cLang.cpp FCGI_Stream.cpp codeclear.cpp errorresponder.cpp logfile.cpp SQLconnector.cpp main.cpp  -o "test.fcgi" -lfcgi++ -lpthread -ljsoncpp -lfcgi
