#!/bin/sh
 
# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e
 
# Must be a valid filename
NAME=interpreter
PIDFILE=/var/run/$SCRIPTNAME.pid
#This is the command to be run, give the full pathname
DAEMON_DIR=/var/www/fcgi/
DAEMON_NAME=test.fcgi
 
export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 
case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
	start-stop-daemon -d $DAEMON_DIR -Sbvmp $PIDFILE -x $DAEMON_DIR$DAEMON_NAME
        echo "."
	;;
  stop)
        echo -n "Stopping daemon: "$NAME
	start-stop-daemon -Kvp $PIDFILE
        echo "."
	;;
  restart)
        echo -n "Restarting daemon: "$NAME
	start-stop-daemon -Kvp $PIDFILE
	start-stop-daemon -d $DAEMON_DIR -Sbvmp $PIDFILE -x $DAEMON_DIR$DAEMON_NAME
	echo "."
	;;
 
  *)
	echo "Usage: "$1" {start|stop|restart}"
	exit 1
esac
 
exit 0
